# Enable rounded corners
corner-radius = 10;

# Excluding certain elements from tiling (such as the top bar, polybar, or i3bar)
rounded-corners-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "class_g = 'Polybar'",
  "class_g = 'i3bar'"
];

# Enable anti-aliasing (smooth edges)
detect-rounded-corners = true;
backend = "glx";
